# emojis.py

# Mapeamento de palavras-chave para emojis
keyword_to_emoji = {
    'celular': '📱',
    'tablet': '📱',
    'notebook': '💻',
    'laptop': '💻',
    'desktop': '💻',
    'teclado': '⌨️',
    'mouse': '🖱️',
    'monitor': '🖥️',
    'impressora': '🖨️',
    'fones de ouvido': '🎧',
    'caixa de som': '🔊',
    'câmera': '📷',
    'smartwatch': '⌚',
    'videogame': '🎮',
    'console': '🎮',
    'smart TV': '📺',
    'micro-ondas': '🍲',
    'geladeira': '❄️',
    'fogão': '🍳',
    'liquidificador': '🥤',
    'cafeteira': '☕',
    'aspirador de pó': '🧹',
    'máquina de lavar': '🧺',
    'secador de cabelo': '💇‍♂️',
    'escova de dentes elétrica': '🪥',
    'ventilador': '🌀',
    'aquecedor': '🔥',
    'bicicleta': '🚲',
    'skate': '🛹',
    'patinete': '🛴',
    'carro': '🚗',
    'moto': '🏍️',
    'carrinho de bebê': '👶',
    'berço': '🛏️',
    'cadeira de escritório': '💺',
    'mesa de escritório': '🪑',
    'sofá': '🛋️',
    'poltrona': '🪑',
    'cama': '🛏️',
    'armário': '🛋️',
    'prateleira': '📚',
    'luminária': '💡',
    'abajur': '🌟',
    'espelho': '🪞',
    'tapete': '🎍',
    'toalha de banho': '🛁',
    'toalha de rosto': '🧼',
    'roupão': '🛀',
    'travesseiro': '🛏️',
    'cobertor': '🛌',
    'almofada': '🛏️',
    'lençol': '🛏️',
    'faca': '🍴',
    'garfo': '🍴',
    'colher': '🍴',
    'panela': '🍳',
    'frigideira': '🍳',
    'prato': '🍽️',
    'copo': '🥛',
    'xícara': '☕',
    'jarra': '🍶',
    'cafeteira': '☕',
    'chaleira': '🫖',
    'tábua de cortar': '🔪',
    'pote de armazenamento': '🍯',
    'balança de cozinha': '⚖️',
    'espremedor de frutas': '🍊',
    'torradeira': '🍞',
    'liquidificador': '🥤',
    'mixer': '🍹',
    'assadeira': '🥧',
    'forma para bolo': '🎂',
    'panela de pressão': '🍲',
    'pipoqueira': '🍿',
    'crepeira': '🥞',
    'waffleira': '🧇',
    'sanduicheira': '🥪',
    'forno elétrico': '🍕',
    'geladeira': '❄️',
    'freezer': '❄️',
    'lava-louças': '🍽️',
    'cafeteira': '☕',
    'batedeira': '🍰',
    'processador de alimentos': '🥗',
    'ferro de passar': '🧺',
    'aspirador de pó': '🧹',
    'máquina de costura': '🧵',
    'máquina de cortar cabelo': '💇‍♂️',
    'escova de dentes elétrica': '🪥',
    'escova de cabelo': '💇‍♂️',
    'secador de cabelo': '💇‍♂️',
    'carrinho de ferramentas': '🛠️',
    'furadeira': '🔩',
    'serra elétrica': '🛠️',
    'parafusadeira': '🔩',
    'lixadeira': '🛠️',
    'soprador térmico': '🛠️',
    'chave de fenda': '🔧',
    'martelo': '🔨',
    'trena': '📏',
    'prego': '🔨',
    'parafuso': '🔩',
    'porca': '🔩',
    'buchas': '🔩',
    'arruela': '🔩',
    'broca': '🪚',
    'serra': '🪚',
    'pendrive': '💽',
    'pen drive': '💽',
    'cremes': '🧴',
    'livros': '📚',
    'máscara facial': '😷',
    'álcool em gel': '🧴',
    'termômetro': '🌡️',
    'luvas descartáveis': '🧤',
    'máquina de oxímetro de pulso': '🩸',
    'oxímetro de dedo': '🩸',
    'kit de primeiros socorros': '⛑️',
    'termômetro infravermelho': '🌡️',
    'medidor de pressão arterial': '🩸',
    'inalador': '💨',
    'nebulizador': '💨',
    'aparelho de pressão digital': '🩸',
    'fita métrica': '📏',
    'medidor de glicose': '🩸',
    'estetoscópio': '🩺',
    'detector de batimentos cardíacos': '🩺',
    'oxímetro de pulso': '🩸',
    'celular': '📱',
    'tablet': '📱',
    'notebook': '💻',
    'laptop': '💻',
    'desktop': '💻',
    'teclado': '⌨️',
    'mouse': '🖱️',
    'monitor': '🖥️',
    'impressora': '🖨️',
    'fones de ouvido': '🎧',
    'caixa de som': '🔊',
    'câmera': '📷',
    'smartwatch': '⌚',
    'videogame': '🎮',
    'console': '🎮',
    'smart TV': '📺',
    'micro-ondas': '🍲',
    'geladeira': '❄️',
    'fogão': '🍳',
    'liquidificador': '🥤',
    'cafeteira': '☕',
    'aspirador de pó': '🧹',
    'máquina de lavar': '🧺',
    'secador de cabelo': '💇‍♂️',
    'escova de dentes elétrica': '🪥',
    'ventilador': '🌀',
    'aquecedor': '🔥',
    'bicicleta': '🚲',
    'skate': '🛹',
    'patinete': '🛴',
    'carro': '🚗',
    'moto': '🏍️',
    'carrinho de bebê': '👶',
    'berço': '🛏️',
    'cadeira de escritório': '💺',
    'mesa de escritório': '🪑',
    'sofá': '🛋️',
    'poltrona': '🪑',
    'cama': '🛏️',
    'armário': '🛋️',
    'prateleira': '📚',
    'luminária': '💡',
    'abajur': '🌟',
    'espelho': '🪞',
    'tapete': '🎍',
    'toalha de banho': '🛁',
    'toalha de rosto': '🧼',
    'roupão': '🛀',
    'travesseiro': '🛏️',
    'cobertor': '🛌',
    'almofada': '🛏️',
    'lençol': '🛏️',
    'faca': '🍴',
    'garfo': '🍴',
    'colher': '🍴',
    'panela': '🍳',
    'frigideira': '🍳',
    'prato': '🍽️',
    'copo': '🥛',
    'xícara': '☕',
    'jarra': '🍶',
    'cafeteira': '☕',
    'chaleira': '🫖',
    'tábua de cortar': '🔪',
    'pote de armazenamento': '🍯',
    'balança de cozinha': '⚖️',
    'espremedor de frutas': '🍊',
    'torradeira': '🍞',
    'liquidificador': '🥤',
    'mixer': '🍹',
    'assadeira': '🥧',
    'forma para bolo': '🎂',
    'panela de pressão': '🍲',
    'pipoqueira': '🍿',
    'crepeira': '🥞',
    'waffleira': '🧇',
    'sanduicheira': '🥪',
    'forno elétrico': '🍕',
    'geladeira': '❄️',
    'freezer': '❄️',
    'lava-louças': '🍽️',
    'cafeteira': '☕',
    'batedeira': '🍰',
    'processador de alimentos': '🥗',
    'ferro de passar': '🧺',
    'aspirador de pó': '🧹',
    'máquina de costura': '🧵',
    # Adicione mais palavras-chave e emojis conforme necessário
}

# Emoji padrão
default_emoji = '⭐'